name: aadhaar_qr_scanner
description: On-device Aadhaar QR scanner and decoder for Flutter using Google ML Kit.
version: 1.0.0
repository: https://github.com/indiap2p/aadhaar_qr_scanner
homepage: https://github.com/indiap2p/aadhaar_qr_scanner

environment:
  sdk: ^3.10.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  xml: ^6.5.0
  archive: ^4.0.7
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.indiap2p.aadhaar_qr_scanner
        pluginClass: AadhaarQrScannerPlugin
